### ISSUE TITLE
Typings of '@pintora/standalone' cannot be imported (IDE only)

### ISSUE THREAD

**Issue by tex0l** [hikerpig/pintora#212]
When importing type `PintoraConfig` from `'@pintora/standalone'`:
```
import type { PintoraConfig } from '@pintora/standalone'
```

I get the following error from my IDE Typescript inspection: 
```
TS7016: Could not find a declaration file for module  @pintora/standalone .
/path/to/project/node_modules/@pintora/standalone/lib/pintora-standalone.esm.js
implicitly has an  any  type.
There are types at
/path/to/project/node_modules/@pintora/standalone/types/index.d.ts
, but this result could not be resolved when respecting package.json  exports . The  @pintora/standalone  library may need to update its package.json or typings.
```

However, when I do it from `'@pintora/core/lib/config'` it works fine.

This happens in WebStorm 2023.2.5, whether I use the bundled TS v5.1.3 or my package's TS v5.3.2, but the code runs fine either way.

**Comment by hikerpig** [comment]
I've tested in some other demo, add a dependency of `"@pintora/standalone": "^0.6.3"` and open it with VSCode and it seems fine.
![image](https://github.com/hikerpig/pintora/assets/2259688/92d53a79-6e4e-4687-b460-277a08651b67)

And `@pintora/standalone` itself has declared `types` field inside package.json which I think should work. Sorry that I don't have Webstorm installed to check this problem.

**Comment by stereobooster** [comment]
It's not just WebStorm - VSCode and tsc have the same issue (on my machine at least).

Plus in Astro project I have this error:

```
(node:84265) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
[ERROR] Unexpected token 'export'
  Stack trace:
    at internalCompileFunction (node:internal/vm:73:18)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29
```

Which goes away if I add:

```
"type": "module",
```

to `node_modules/.pnpm/@pintora+standalone@0.6.5/node_modules/@pintora/standalone/package.json`

**Comment by hikerpig** [comment]
It may be a problem above certain typescript version. I might have been solved it in this commit https://github.com/hikerpig/pintora/pull/233/files#diff-6b7dd58480a1e85dc2f1449f587216c986a713cc4e2345c4c168c46b862da5a8R19  . But we will wait till the next alpha version to see if it really works.

**Comment by hikerpig** [comment]
Try `@pintora/standalone@0.7.0-alpha.0`

**Comment by stereobooster** [comment]
Yes this solves problem with TypeScript, but I still see `Unexpected token 'export'`

**Comment by hikerpig** [comment]
@stereobooster I see. @pintora/standalone's package was meant to be used by a bundler before so this may not be an issue.
I will consider adding the 'type: module' this week, after some tests in some of my projects.

**Comment by hikerpig** [comment]
@stereobooster Emm I start to think that we shouldn't alter type of in @pintora/standalone because it did provides UMD and ESM output files.
Instead, this seems to be an issue of importing directly from Node.js without a bundler.
It may be solved by providing a `.mjs` output file.
![image](https://github.com/hikerpig/pintora/assets/2259688/0b6b77b3-8134-41ec-93c3-d0244ed0fb97)
